### ISSUE TITLE
Update the Netbeans plugin page

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#1]
* License is wrong - your code seems to be Apache 2.0
* Add link to https://github.com/Revivius/nb-darcula/
![2016-01-19_21h41_20](https://cloud.githubusercontent.com/assets/1857095/12431391/7d5fee98-bef5-11e5-813d-e25404ac935f.png)

**Comment by Revivius** [comment]
License updated.

**Comment by markiewb** [comment]
Fine!
