### ISSUE TITLE
Colors in code completion for scss variables are not readable

### ISSUE THREAD

**Issue by emilime** [Revivius/nb-darcula#103]
Variable name suggestions in scss files are not readable, see attachment:
![screenclip 9](https://cloud.githubusercontent.com/assets/47943/14869927/f6aac014-0cd6-11e6-8c47-b6cbe6498357.png)

**Comment by Revivius** [comment]
@emilime; this was reported in #91 and fixed in commit 3f55d4659973eaf1c5741d288484d2faf3f77518. Closing this issue, fix will be available in next version.
