### ISSUE TITLE
Colors on hit breakpoint are unreadable

### ISSUE THREAD

**Issue by cowwoc** [Revivius/nb-darcula#110]
If you set a breakpoint and it is hit, you end up with:

![screenshot](https://cloud.githubusercontent.com/assets/633348/15612006/fbaa56b6-23fa-11e6-878e-a64f2a7ed682.png)

Black text on a dark green background is unreadable. The "final" keyword (light blue against a dark green background) is also unreadable.

**Comment by cowwoc** [comment]
Sorry for the false alarm. Darcula was not installed properly. The Darcula text/color profile was set, but the plugin was not installed. Closing this issue.

**Comment by Chris2011** [comment]
I still have the problem, the darcula theme is installed well and if it stops at a breakpoint, the highlighted color is green and the thing behind is unreadable. Please reopen this ticket.

**Comment by Chris2011** [comment]
I fixed it, because I used the Atom colors and not the darcula theme color profile.
