### ISSUE TITLE
url link not working http://plugins.netbeans.org/plugin/62424/darcula-laf-for-netbeans

### ISSUE THREAD

**Issue by tnchuntic** [Revivius/nb-darcula#111]
Hi just to inform you that link http://plugins.netbeans.org/plugin/62424/darcula-laf-for-netbeans is not working. I have tried accessing it in both install plugin and manual still url link not working.

Thanks

**Comment by markiewb** [comment]
The whole plugin center is offline: http://plugins.netbeans.org/

**Comment by roy187** [comment]
wth is going on with the plugin site, emergency!!@

**Comment by iMiiTH** [comment]
https://twitter.com/netbeans/status/742779437704486916

The Netbeans team was working on the site. It's been up for a few days now.

**Comment by Revivius** [comment]
Closing.
