### ISSUE TITLE
L&F prevents installation of Netbeans updates

### ISSUE THREAD

**Issue by cowwoc** [Revivius/nb-darcula#115]
Repro steps:
1. Install Netbeans 8.1 (Java SE edition)
2. Install Darcula 1.5
3. Help -> Check for Updates -> apply all
4. Restart Netbeans
5. Splash screen will reach 100% but then the process shuts down.
6. Check messages.log, notice that Darcula is preventing Netbeans from launching.

Deleting the userdir and cache directory does not help. The only solution is to completely reinstall Netbeans and not update (and even then you need to manually delete the lockfile for the uninstaller to proceed).

See https://netbeans.org/bugzilla/show_bug.cgi?id=262243 for more details.

**Comment by Revivius** [comment]
@cowwoc, sorry for late reply but I can not reproduce the problem. Is this still relevant ?

**Comment by cowwoc** [comment]
@Revivius At last check, it was. Give me a week, I will try against the latest dev build and report back here.

**Comment by cowwoc** [comment]
Confirmed. It looks like this was a bug in Netbeans and they fixed it on their end.
