### ISSUE TITLE
Nb-darcula responsible for new added language which is unreadable?

### ISSUE THREAD

**Issue by Chris2011** [Revivius/nb-darcula#116]
I tried a plugin called nbshell (http://plugins.netbeans.org/plugin/68049/nbshell), which brings code completion for shell scripts to netbeans and syntax highlighting. The Color is a bit to dark and the code completion items are not readable.

The question what I have is who is responsible for new added languages to netbeans when using nb-darcula? Is there a common problem with font colors or is this a specific problem from the nbshell plugin? Can you clarify this?

Cheers

Chris

**Comment by Revivius** [comment]
@Chris2011; please see:

https://netbeans.org/bugzilla/show_bug.cgi?id=257867

**Comment by Chris2011** [comment]
thx :)

**Comment by Revivius** [comment]
Closing the issue.
