### ISSUE TITLE
How to configure as project in netbeans 8.1

### ISSUE THREAD

**Issue by sureshamk** [Revivius/nb-darcula#117]
I would like to contribute , due to new to this netbeans platforms i trying to make this repo as netbeans module project . Is any one give way to achieve this ?

**Comment by markiewb** [comment]
The project is already a NetBeans project. But a Maven-based one, which is easier to maintain and contribute to than a Ant-based one!

If you want to contribute take one of the issues from https://github.com/Revivius/nb-darcula/issues and provide a pull request!

**Comment by markiewb** [comment]
@Revivius: My proposal is to close this issue

**Comment by Revivius** [comment]
@sureshamk; you want to know how to include this in a NetBeans platform application ?

**Comment by sureshamk** [comment]
Hi  @Revivius i done with adding as maven project .. Thanks man
