### ISSUE TITLE
Icons and text jumps for selected entries

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#119]
![2016-08-01 22h47_05](https://cloud.githubusercontent.com/assets/1857095/17308525/d40a37a6-583a-11e6-92c2-68fd24d0cb2c.gif)
![2016-08-01 22h47_58](https://cloud.githubusercontent.com/assets/1857095/17308529/d697bafc-583a-11e6-8cc1-1634efc15ca4.gif)

**Comment by markiewb** [comment]
@Revivius: Please integrate my pull request https://github.com/Revivius/nb-darcula/pull/120

Now it is working properly

![2016-08-01 22h43_32](https://cloud.githubusercontent.com/assets/1857095/17308745/d1567dc0-583b-11e6-9ea5-9f2353c7e2ef.gif)
![2016-08-01 22h44_32](https://cloud.githubusercontent.com/assets/1857095/17308750/d2bd56c0-583b-11e6-85f4-95d4ec1a45a5.gif)

**Comment by markiewb** [comment]
@Revivius: Could you please integrate my pull request! Do you still support this plugin officially? It has been quite silent since several weeks...

**Comment by Revivius** [comment]
@markiewb, sorry for the delay.

Btw, yes, I plan keeping take care of this plugin, just requested verification for NB 8.2 in plugin portal.

**Comment by markiewb** [comment]
@Revivius: At the plugin center there is still version 1.5?! Something got wrong? And there are open pull requests and #118

**Comment by markiewb** [comment]
Thanks for merging btw
