### ISSUE TITLE
Color blends

### ISSUE THREAD

**Issue by rvillablanca** [Revivius/nb-darcula#123]
Is there any posibility to change color of the text?
`(The text will be used literally)`

![search](https://cloud.githubusercontent.com/assets/1508272/18210347/73cfa62c-710e-11e6-87dc-b7bff0a6341e.png)

**Comment by markiewb** [comment]
What exactly do you mean?

**Comment by Saljack** [comment]
It is help text under two inputs (Containing Text and File Name Patterns). 

- The text will be used literally
- Example *.java FZP??.jsp
![colorblend](https://cloud.githubusercontent.com/assets/614424/18238562/6986a030-733e-11e6-8753-6b2e62a4cc9d.PNG)

**Comment by rvillablanca** [comment]
In my screenshot the help text color is similar to the background color and sometimes it is dificult to view it. 

I am using netbeans under debian linux. But in windows looks like different (showed in the @Saljack comment).

**Comment by markiewb** [comment]
The reason is in http://hg.netbeans.org/core-main/file/tip/api.search/src/org/netbeans/modules/search/BasicSearchForm.java not in the Darcula code.

`.setForeground(SystemColor.controlDkShadow);` is used several times. A better idea would be using disabled labels.

File an issue at https://netbeans.org/bugzilla/, set me to CC so that I can fix it later.

**Comment by rvillablanca** [comment]
I did not know how to copy you to the CC, but here is the bug.

https://netbeans.org/bugzilla/show_bug.cgi?id=267957

Thanks!

**Comment by markiewb** [comment]
https://netbeans.org/bugzilla/show_bug.cgi?id=267957 is fixed. But the change will not be included in the upcoming 8.2 release. But you will find it in the dev builds.

@Revivius: So please resolve as fixed.

**Comment by rvillablanca** [comment]
Too many thanks @Revivius  @markiewb

**Comment by Revivius** [comment]
@rvillablanca , @markiewb closing as fixed as suggested.
