### ISSUE TITLE
Control+PageUp/Down don't work on netbeans 8.2

### ISSUE THREAD

**Issue by okvorb** [Revivius/nb-darcula#126]
Hi

Recently I upgraded netbeans from 8.1 to 8.2 and noticed that Ctrl+PageUp/Down shortcut doesn't work anymore. I thought it's netbeans issue itself, but then I tried fresh installation and found that shortcut don't work only with darcula theme.

**Comment by markiewb** [comment]
Duplicate of #114!

**Comment by Revivius** [comment]
Fixed in 6fd446377913bc9b2f4891430307354997973702. Thanks to @markiewb.
