### ISSUE TITLE
PHP Variables not well readable

### ISSUE THREAD

**Issue by Chris2011** [Revivius/nb-darcula#129]
As you can see in my screenshot, it is hard to read the PHP variables.

![php dark](https://cloud.githubusercontent.com/assets/795658/19762124/e86dc7c0-9c38-11e6-9442-6d05142088b5.PNG)

**Comment by Ravaelles** [comment]
It looks differently on my machine:
http://prntscr.com/ddzjps

Try fresh NB installation or remove previous plugins like Dark Look and Feel, I think they're messing up.

**Comment by Chris2011** [comment]
We can close this, the problem is that I use Darcular laf but an other editor theme, it is atom. I switched to Darcula theme too.
