### ISSUE TITLE
Small Toolbar Icon 

### ISSUE THREAD

**Issue by Saljack** [Revivius/nb-darcula#13]
If I set Small Toolbar Icon than icons are small but toolbar height is same. It is visible on memory consumption monitor. 
![smalltoolbar](https://cloud.githubusercontent.com/assets/614424/12504451/e05fded8-c0dd-11e5-9fe9-25e0dd90ea37.PNG)
![bigiconsmalltoolbar](https://cloud.githubusercontent.com/assets/614424/12504454/e2ce4830-c0dd-11e5-8141-3448f6ee4a09.PNG)
![smalltoolbardracula](https://cloud.githubusercontent.com/assets/614424/12504456/e5032440-c0dd-11e5-8bd6-6f2a5c3d8527.PNG)

.

**Comment by markiewb** [comment]
Is the line of issue? https://github.com/Revivius/nb-darcula/blob/4d91e9c79a023f5db0df983d13e30bf4a9ae24b2/src/main/java/com/revivius/nb/darcula/ToolbarXP.java#L100

**Comment by Revivius** [comment]
Yes indeed @markiewb! Done:

![small_toolbar](https://cloud.githubusercontent.com/assets/7155989/12525610/30c10a1a-c16e-11e5-9f77-8012abe4f95f.png)
