### ISSUE TITLE
Select in Projects shortcut doesn't work

### ISSUE THREAD

**Issue by Saljack** [Revivius/nb-darcula#132]
Hi Select in Projects shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> doesn't work from Editor with focus. Select in Files <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd> and Select in Favorites <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>3</kbd> are working. If I first press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd> and after <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> file is selected in Projects window. Select in Projects works if I do it from menu (Navigate -> Select in Projects).  Shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> is working with default LAF. 

1. Open file from Projects window
2. Click to source code
3. Press  <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd>
4. Nothing happen. Expected: Current file is selected in Projects window

**Comment by Revivius** [comment]
@Saljack; it works for me in NB 8.2. Please reopen the issue if problem still exists for you.

**Comment by Saljack** [comment]
Problem is actual in NB 8.2 (Linux and Windows). I am not able reopen this issue. Can you please reopen it.

**Comment by Chris2011** [comment]
I can't reproduce it too. I use ctrl + shift +1 for select in project, ctrl + shift + 2 for select in files and so on. And I use NB 8.2 patch 2 and darcula.

**Comment by Saljack** [comment]
It is working ok with current snapshot of nb-darcula.

**Comment by Chris2011** [comment]
DId you build the source? I can't find version 1.6.

**Comment by Saljack** [comment]
Yes I build it from the source.

**Comment by Revivius** [comment]
@Saljack; @Chris2011 I have uploaded v1.6 for NetBeans 8.2 and requested verification. I hope it will be available in Update Center soon.
