### ISSUE TITLE
SQL results output is not good readable

### ISSUE THREAD

**Issue by Chris2011** [Revivius/nb-darcula#133]
As you can see it here: 
![sql-output](https://cloud.githubusercontent.com/assets/795658/21311632/6d169528-c5e8-11e6-8dde-708d2635be3b.png) the lines are to bright, the text is a bit darker than the lines and you have the even/odd color changing of the rows, which is in general good but in this case it is not as good as readable. I prefer the DataGrip view more: 
![sql-output-datagrip](https://cloud.githubusercontent.com/assets/795658/21311711/f11f88e8-c5e8-11e6-9e8d-f71f3e122071.png) this is better readable. It is not that it should look like DataGrip in general, the problem is the readability of the table.

Another suggestion is to remove the linear gradient from the column heads. This has nothing todo with readability.

**Comment by Chris2011** [comment]
For more NetBeans laf I would prefer to have the same style as inside the results window of the profiler: 
![profiler-table](https://cloud.githubusercontent.com/assets/795658/21316390/c5e7eba8-c600-11e6-8346-ad1f3d7f4067.png) enough readable. So please adapt the style from the table of the profiler results window.

**Comment by AlexFalappa** [comment]
I noticed this myself too.
I also noticed that the styling of the SQL result table changed in *NetBeans 8.2*.
The table border lines in *NetBeans 8.1* are dark grey (or black, I don't remember precisely).

**Comment by AlexFalappa** [comment]
I suspect there are some new hardcoded colors in NetBeans code.
Let's see what @Revivius says.

**Comment by Revivius** [comment]
@Chris2011, @AlexFalappa I have just checked and confirm that colors in SQL results table changed. Lets see what is causing this.

**Comment by Chris2011** [comment]
Anything new here?

**Comment by Revivius** [comment]
@Chris2011, @AlexFalappa It looks like there were a couple changes to better support dark themes in db.dataview module in NB 8.2. I hope grid and edited value colors are better now:

![sql-results](https://user-images.githubusercontent.com/7155989/28744079-55c6c158-7462-11e7-8da6-f15dc8f69b8c.png)


Remove gadient from column headers would be too much effort. Closing the issue, please reopen if you have further suggestions.
