### ISSUE TITLE
CSS Preprocessor autocomplate list is not good readable

### ISSUE THREAD

**Issue by proger-su** [Revivius/nb-darcula#135]
![1488441693435](https://cloud.githubusercontent.com/assets/15267639/23498341/053d2f08-ff30-11e6-9489-6b7ee306bbc3.jpg)

**Comment by Revivius** [comment]
@proger-su; with NB 8.2 patch 2 should be better:

![css-mixins](https://user-images.githubusercontent.com/7155989/28744674-afaadfcc-746e-11e7-945a-c1d1feaf016d.png)

**Comment by proger-su** [comment]
Perfect
