### ISSUE TITLE
Setting the default font to large sizes causes some UI elements to be clipped (High DPI display issue)

### ISSUE THREAD

**Issue by nureyev** [Revivius/nb-darcula#138]
If the 'Override default font size' option is used to set the font size to large values some UI elements start getting clipped or cut off. I'm not sure if this is a Darcula issue or inherent to NetBeans.

For example, I set the font to Segoe UI, 22 point:

![nb_persistence_rs](https://cloud.githubusercontent.com/assets/18418518/25554777/7c4ab330-2cd6-11e7-95f7-09eb21a23a4f.JPG)

![nb_keymap_rs](https://cloud.githubusercontent.com/assets/18418518/25554782/8c663122-2cd6-11e7-8250-b85ebbceccc7.JPG)

**Comment by Revivius** [comment]
@nureyev I think this is a NetBeans issue. Please report to NetBeans.
