### ISSUE TITLE
Default button behaviour does not work as expected.

### ISSUE THREAD

**Issue by Saljack** [Revivius/nb-darcula#14]
Enter focus is lost in some dialogs. For example if I want insert code (ALT+Insert) than I choose Constructor and press enter nothing happens. This is different behavier from default LAF. 

Next example. I have project with some warning and I want Find Usages. First dialog has focus on find and everything is ok if I press enter. Second step (dialog with warning) do nothing after press enter. But focus look like on Find.
![findusage](https://cloud.githubusercontent.com/assets/614424/12504670/0f25ec38-c0e0-11e5-9606-0d215393868b.png)

**Comment by Revivius** [comment]
@Saljack both works for me. Can you verify the issue please ?

**Comment by dylanvorster** [comment]
Steps to reproduce on Mac:

* Go to class
* Click somewhere in class file, must be directly inside class, not in a method call/constructor
* CTRL + i (insert code)
* Select override and Implement method / Insert Getters and Setters
* Select something press enter
* Nothing happens.

Its worth noting that in the screenshot by @Saljack clearly has a focus set on the 'Find' button while my screenshot does not but also doesn't work, even though the Ok button is clearly supposed to be selected.
<img width="607" alt="screen shot 2016-01-24 at 8 12 28 pm" src="https://cloud.githubusercontent.com/assets/6099427/12538026/e2de1b70-c2d6-11e5-9e51-ccc951da7460.png">

**Comment by Saljack** [comment]
If I use Windows LAF everything works ok. So my scenario is:

1. Press Alt + Insert (Insert code)
2. Select Getter and Setter
3. Select some field with space
4. Press Enter
5. Nothing happen (expected insert generated setter and getter methods)

There are screenshot from insert dialog:
![insertcodenormal](https://cloud.githubusercontent.com/assets/614424/12547019/010bae4c-c34e-11e5-8e89-7b54b110af1b.png)
![insertcode](https://cloud.githubusercontent.com/assets/614424/12547022/040e4a1e-c34e-11e5-9a32-f9af0754e2e8.PNG)

**Comment by markiewb** [comment]
So the default-button behavior does not work using this LAF.

@Revivius: Can you please rename this issue accordingly 

Producible for me
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java: 1.8.0_71; Java HotSpot(TM) 64-Bit Server VM 25.71-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_71-b15
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)

**Comment by markiewb** [comment]
@Revivius: https://tips4java.wordpress.com/2008/10/25/enter-key-and-button/

**Comment by markiewb** [comment]
@Revivius: Also have a look at the sources of https://github.com/JetBrains/intellij-community/tree/master/platform/platform-impl/src/com/intellij/ide/ui/laf Perhaps the guys at JB fixed such an issue?

**Comment by Revivius** [comment]
@markiewb setting "Button.defaultButtonFollowsFocus" to TRUE did not help, may be related to:

https://netbeans.org/bugzilla/show_bug.cgi?id=149102

**Comment by markiewb** [comment]
@Revivius: Yes. I also tried it out and it did not work. Perhaps the LAF alters the "inputMap"/"actionInputMap" of JPanels/JTrees?

JTrees, because in all the screenshot there are trees, which do not delegate the ENTER-key.

**Comment by Revivius** [comment]
@markiewb I also tried to use BasicTreeUI and MetalTreeUI instead of DarculaTreeUI but no change. I cant see anything that modifies input map of JTrees also.

**Comment by Revivius** [comment]
@Saljack thank you for reporting and @dylanvorster for clarifying. 

and @markiewb thank you once more for pointing me to right direction. With this fixed I think we are ready for v1.4.

**Comment by markiewb** [comment]
@Revivius:

https://github.com/Revivius/nb-darcula/commit/f9ece35cc348f442e295c75feabede5f534cbc9c#diff-9fbfce4e959f187cc27903ee921c1824L441

Why did you remove the invertIcon-feature from https://github.com/Revivius/nb-darcula/pull/41 ? Accidentally? maybeEnableIconFilter was introduced, but never used - at least in that commit!

**Comment by Revivius** [comment]
@markiewb it was an accidentall commit and i have corrected it. Last commit uses maybeEnableIconFilter.

**Comment by markiewb** [comment]
@Revivius: Ok, yes you are correct. I found it https://github.com/Revivius/nb-darcula/commit/aa46792f71028c29dfb9e709e90fa1095bf2d98e#diff-9fbfce4e959f187cc27903ee921c1824R446

**Comment by markiewb** [comment]
Cool. It really works. Tested with toString/getter/setter code generator.

**Comment by Revivius** [comment]
Good to know!
