### ISSUE TITLE
Editor tab color

### ISSUE THREAD

**Issue by johnmanko** [Revivius/nb-darcula#140]
I'd like to contribute to this theme by adding an option to change the editor's active tab color (the current one, which varies very slightly from other opened tabs, is too hard for my poor eyes to differentiate :).

Where in the code base is the tab color set?

**Comment by Revivius** [comment]
I hope it is better now; (hard to find a color that is ligther than inactive tabs but darker than the font color):

![active-tab](https://user-images.githubusercontent.com/7155989/28744046-a49c60d6-7461-11e7-8214-26d90574786d.png)

**Comment by Chris2011** [comment]
Hm, my active editor tab is blue, was this implemented later? I want to remove the blue color from my tab.
