### ISSUE TITLE
Project tree indentation

### ISSUE THREAD

**Issue by riksoft** [Revivius/nb-darcula#142]
Hi there,
I have Darcula on Netbeans 8.2 and I was wondering whether there is any way, e.g changing some config files, to increase the indentation of files/folders icons in the project/file window. Sometimes I get lost in huge projects.

**Comment by Revivius** [comment]
Darcula Look And Feel panel and now includes 'Override tree indent' option:

![tree-indent](https://user-images.githubusercontent.com/7155989/28751465-14616a24-7511-11e7-81dc-945a73810ab9.png)

**Comment by riksoft** [comment]
Yeeeeeee!  :+1: 
Thanks a lot!
