### ISSUE TITLE
Bright gaps in visual designer

### ISSUE THREAD

**Issue by AlexFalappa** [Revivius/nb-darcula#15]
The gaps in the visual GUI designer when editing forms in the *Free Design* mode (`javax.swing.GroupLayout`) are drawn with a brighter color than the widgets, they are too distracting.
Example:
![netbeans_visual_editor](https://cloud.githubusercontent.com/assets/1875690/12510682/00637504-c10c-11e5-82e0-f34bfb424f0a.png)

**Comment by granella** [comment]
@AlexFalappa The main problem is to match the border color with background. I don't have found a way to change the border color yet.

Test of gap transparent background:
![screenshot from 2016-01-23 16-05-19](https://cloud.githubusercontent.com/assets/859038/12531948/614469cc-c1ee-11e5-951a-32ec28d71077.png)

**Comment by Revivius** [comment]
@AlexFalappa, @granella gap border and saw colors are seem to be hardcoded in .LayoutPainter. ()
```java

package org.netbeans.modules.form.layoutdesign;

public class LayoutPainter implements LayoutConstants {
    ...
    private static Color gapBorderColor = new Color(200, 200, 200); // 192, 192, 192
    private static Color sawColor = new Color(208, 208, 208);
    ...
}
```

So back to reflection:

![designer](https://cloud.githubusercontent.com/assets/7155989/12533525/7a3f2e20-c23a-11e5-9ba2-e0884f644223.png)

**Comment by AlexFalappa** [comment]
@Revivius you should report the use of hardcoded colors you found opening a bug in NetBeans bugzilla.

IMHO all the colors should either come from the active L&F or be at least programmatically changeable.

NetBeans should improve themeability.

**Comment by Revivius** [comment]
@AlexFalappa I have already reported, but now added designer gap borders too. Here:

https://netbeans.org/bugzilla/show_bug.cgi?id=257675

Thank you.

**Comment by AlexFalappa** [comment]
Sure will do.

**Comment by markiewb** [comment]
Voted. 

BTW: @Revivius: Sign a OCA and you can provide patches for NB! Or provide a patch and I'll send it in!
