### ISSUE TITLE
"Test Packages" and "Other Test Sources" node icons should have different (green?) color in the project tree

### ISSUE THREAD

**Issue by gyszalai** [Revivius/nb-darcula#16]
It's very handy in IDEA. I don't know if NetBeans platform supports it or not, though.

**Comment by Revivius** [comment]
@gyszalai it is sure possible but not in LAF level. Please create an issue in NetBeans bugzilla, sure that I would vote for it.

**Comment by dylanvorster** [comment]
Can we close this issue seeing as its not actually related to the LAF, but to the core IDE?

**Comment by gyszalai** [comment]
@Revivius Just created an issue in Netbeans' bugzilla: https://netbeans.org/bugzilla/show_bug.cgi?id=257703

@dylanvorster Yes, I think it can be closed.

**Comment by Revivius** [comment]
@gyszalai voted for it! Closing.

**Comment by markiewb** [comment]
Voted too!
