### ISSUE TITLE
GUI Builder Colors

### ISSUE THREAD

**Issue by intesisdev** [Revivius/nb-darcula#167]
When the theme is applied the swing forms on the builder/preview also turns to Darcula. Is there a way to change only the GUI Builder to the 'Windows' look and feel?

**Comment by AlexFalappa** [comment]
NetBeans is a Java Swing application and with Swing it is not possible to have only part of the GUI with a different Look&Feel, thus it is not a bug of Darcula but a limitation of the Swing toolkit.

As a workaround I could suggest to right click on the node representing the top container in the navigator view (e.g. your JFrame or JPanel) and choose `Preview Design > Windows`: this will launch a temporary window with your swing form in a different Look And Feel.

**Comment by intesisdev** [comment]
Ok. Thanks for the reply. I'm closing the issue.
