### ISSUE TITLE
SplitPane divider collapse buttons and indicator missing

### ISSUE THREAD

**Issue by Revivius** [Revivius/nb-darcula#18]
One touch collapse buttons of divider in JSplitPane is missing. Also there is no split indication.

![splitpane](https://cloud.githubusercontent.com/assets/7155989/12524490/00ebecae-c166-11e5-96fc-511f2b5b29bc.png)

**Comment by Revivius** [comment]
Done:

![splitpane](https://cloud.githubusercontent.com/assets/7155989/12525291/fcd8fca0-c16b-11e5-8104-72314b8fb344.png)

**Comment by markiewb** [comment]
@Revivius: Thanks for the fix. But you should at least acknowledge the source origin/authors, where you got the code from.

https://github.com/bulenkov/Darcula/pull/5

**Comment by Revivius** [comment]
I would if I could remember :) Will acknowledge hudsonb (Brian Hudson) in next commit. Thanks for pointing out.

**Comment by markiewb** [comment]
@Revivius: This was only a reminder. Nothing serious. You can add him in the README.me
