### ISSUE TITLE
Default font is bold, but shouldn't be

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#2]
![image](https://cloud.githubusercontent.com/assets/1857095/12431537/43882518-bef6-11e5-8ca3-da35f290d067.png)

**Comment by markiewb** [comment]
In Idea 15 no bold font is used
![image](https://cloud.githubusercontent.com/assets/1857095/12462247/8cfb0e46-bfbd-11e5-87d8-5b105659b636.png)

**Comment by markiewb** [comment]
See my pull request
https://github.com/markiewb/nb-darcula/tree/feature/nonboldsizefonts

Or even better
https://github.com/Revivius/nb-darcula/pull/8 (which solves more issues)

**Comment by markiewb** [comment]
See also https://github.com/Revivius/nb-darcula/pull/12

**Comment by Revivius** [comment]
Fixed with contribution from @markiewb.

**Comment by markiewb** [comment]
@Revivius: Please create a new milestone (/version) 1.3 and assign each recently fixed issue to this version. This way it is easier to track, which issues have been fixed since 1.2. And it's easier to write release notes.
