### ISSUE TITLE
The LAF is very fashionable, but some icons are not.

### ISSUE THREAD

**Issue by ZMichaelChow** [Revivius/nb-darcula#20]
I really appreciate that you did such a wonderful thing, the darcula fits Netbeans really well. But,  personally I think some icons do not fit this LAF, such as I marked below:
![n1](https://cloud.githubusercontent.com/assets/15724596/12530607/e4051bec-c21e-11e5-9393-bc9094dade44.png)
Do you think so?

**Comment by Revivius** [comment]
@ZMichaelChow 
I believe dotted icons in TopComponent headers make it easier to distinguish them. Otherwise fixed:

![icons](https://cloud.githubusercontent.com/assets/7155989/12537215/3d51a1c2-c2c2-11e5-9024-6cfc4b7109d2.png)

**Comment by ZMichaelChow** [comment]
Good job!
Haha, perhaps there are no dotted icons in other LAFs and we have become accustomed to it :) , eg:
Windows:
![1](https://cloud.githubusercontent.com/assets/15724596/12549540/e82a59e6-c398-11e5-8c8b-c556416ef6d3.PNG)
Nimbus:
![2](https://cloud.githubusercontent.com/assets/15724596/12549546/f2013c3c-c398-11e5-85b2-2141c4b662e8.PNG)
In IDEA:
"Project" has it's own noticeable icon:
![4](https://cloud.githubusercontent.com/assets/15724596/12549731/2b3f1144-c39a-11e5-9f07-639869fe54b5.PNG)
And other TopComponent headers are without icons, eg:
![3](https://cloud.githubusercontent.com/assets/15724596/12549701/09cfa186-c39a-11e5-969e-c1c277914358.PNG)
![5](https://cloud.githubusercontent.com/assets/15724596/12549709/1118b2b6-c39a-11e5-916c-bd2f35dc34c3.PNG)
If I were you, I'll remove the dotted icons. It's only a suggestion, you can do what you like~
