### ISSUE TITLE
color problem when instantiating object from PHP class in dropdown

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#21]
When attempting to create a new object from a PHP class and the dropdown is triggered, the color of the classnames are red.

<img width="524" alt="screen shot 2016-01-24 at 7 35 32 pm" src="https://cloud.githubusercontent.com/assets/6099427/12537819/d95c5a8a-c2d1-11e5-9b19-23836c773a38.png">

**Comment by Revivius** [comment]
Fixed (for PHP and hopefully for all languages):

![cc-classes](https://cloud.githubusercontent.com/assets/7155989/12695836/78520ef2-c762-11e5-8c2d-20a9295e2f8e.png)
