### ISSUE TITLE
Some labels in project pane (potentially other places) hard to read

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#22]
See attached screenshot
<img width="637" alt="screen shot 2016-01-24 at 7 38 51 pm" src="https://cloud.githubusercontent.com/assets/6099427/12537840/55691a5a-c2d2-11e5-83f0-bcbc81d896f9.png">

If I find more like this, ill post them in this issue

**Comment by dylanvorster** [comment]
Found some more examples, and while I'm aware in this specific case, that the items are deactivated, I would argue we should rather just keep the main color, but make the labels about 50% transparent from the original foreground. This way we can still read the labels even if they are deactivated, as this is helpful when we are sometimes looking for a setting (or similar type of feature), which may require us to enable some radio button first. In in any case, I don't think the text shadow looks good anyways, we should try stay away from insets in general with this theme. Not sure how difficult it is to fix this though, as it might be part of the Dracula LAF.
<img width="905" alt="screen shot 2016-01-24 at 7 46 02 pm" src="https://cloud.githubusercontent.com/assets/6099427/12537879/94cf391c-c2d3-11e5-9bd4-e524fe9f75fd.png">

**Comment by markiewb** [comment]
![2016-01-25_08h11_01](https://cloud.githubusercontent.com/assets/1857095/12544532/45911f9c-c33b-11e5-81fc-20d3f14cfcbc.png)

Here an example, how disabled controls look like in Idea15. There is no shadow

**Comment by Revivius** [comment]
This have many duplicates now, @granella  seems to solve the issue with his PR #35. Will fix in v1.4.

**Comment by Revivius** [comment]
Deactivated labels fixed by PR #35 thanks to @granella. I will fix buttons in a different issue. Thanks for reporting.

**Comment by markiewb** [comment]
@granella: I will fix buttons in a different issue. Thanks for reporting. > I filed #38 for you!
