### ISSUE TITLE
Small "..." button in Project Properties > JS Frameworks > RequireJS

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#23]
<img width="703" alt="screen shot 2016-01-24 at 7 41 31 pm" src="https://cloud.githubusercontent.com/assets/6099427/12537854/c98b6366-c2d2-11e5-8ea5-d7719a8dabad.png">

Funny enough, this button is not always visible even when running the default LAF, to see the button, you first need to click on the first row, which is in itself an issue because its not always obvious that its there.

**Comment by Revivius** [comment]
@dylanvorster; more digging in NetBeans sources and:

http://hg.netbeans.org/main/file/084fe1e7e4ba/javascript2.requirejs/src/org/netbeans/modules/javascript2/requirejs/ui/LocalPathCell.java

```java
line 106: localPathBrowseButton.setBorder(BorderFactory.createLineBorder(UIManager.getDefaults().getColor("activeCaptionBorder")));
```

It is easy to change **activeCaptionBorder** but I dont know which other places it would effect.

**Comment by Revivius** [comment]
I edited the title because this is really specific to the RequireJS configuration and not to all browse path buttons.

**Comment by Revivius** [comment]
Closing the issue. @dylanvorster please comment if you have any suggestions.
