### ISSUE TITLE
White border on hidden toolbar icons popup window

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#24]
See screenshot

<img width="230" alt="screen shot 2016-01-24 at 7 50 40 pm" src="https://cloud.githubusercontent.com/assets/6099427/12537891/e73cd3c6-c2d3-11e5-8ec8-c88fbded7522.png">

**Comment by Revivius** [comment]
![toolbar](https://cloud.githubusercontent.com/assets/7155989/12588651/5379893c-c462-11e5-8f3a-4a24e945c188.png)
