### ISSUE TITLE
Not Important: Consider screenshot in README.md

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#25]
Much like on the project page, I think it would be a good idea to get a screenshot included into the Readme that shows off the entire IDE, perhaps use the same one thats on the plugin page?

Edit: I see the image was actually changed on the plugin page, my browser was probably just caching it.

**Comment by markiewb** [comment]
@Revivius: A small task for you is left in 1.4! *g*

**Comment by Revivius** [comment]
Updated the README and included a screenhot.
