### ISSUE TITLE
PHP keywords are showing up as dark blue, should be lighter (perhaps RGB(0,192,255))

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#26]
<img width="663" alt="screen shot 2016-01-24 at 7 59 14 pm" src="https://cloud.githubusercontent.com/assets/6099427/12537970/93742184-c2d5-11e5-9bc7-bda99a2b1f62.png">

**Comment by bobsta63** [comment]
+1 for this request 

@Revivius - You're doing an excellent job and just wanted to say that I really love the look of Netbeans now!! - Your time and effort are truly appreciated!

**Comment by 4ppleboy** [comment]
+1 for this request 
![screenshot_2016-01-27_10-14-36](https://cloud.githubusercontent.com/assets/3277751/12603670/8e4df95c-c4d6-11e5-8335-e337d68e87f2.png)

**Comment by Revivius** [comment]
Fixed (for PHP and hopefully for all languages):

![cc-keywords](https://cloud.githubusercontent.com/assets/7155989/12695857/2032c328-c763-11e5-91c3-80184fabb05b.png)

**Comment by Revivius** [comment]
Some more fixed code completion colors:

![cc-all](https://cloud.githubusercontent.com/assets/7155989/12695868/6e085798-c763-11e5-92c3-ecd93de1cb50.png)
