### ISSUE TITLE
Not Important: Consider URL to Netbeans plugin page in README.md

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#27]
Might be a good idea to have the URL http://plugins.netbeans.org/plugin/62424/darcula-laf-for-netbeans somewhere at the top of the README.md so that users can quickly get there to download it for the IDE. Might also be a good idea to upload the releases here on Github, so users can quickly try some of the builds, as they would most likely be catalogued

**Comment by Revivius** [comment]
Fixed by @markiewb in PR #28. Thank you both!
