### ISSUE TITLE
Version 1.3 includes Java 8 compiled classes

### ISSUE THREAD

**Issue by AlexFalappa** [Revivius/nb-darcula#29]
After upgrading to version 1.3 on a NetBeans 8.1 running on Java 7 I got an `UnsupportedClassVersionError` exception.

It seems the last version includes a DarculaLAF (`darcula.jar`) compiled with **Java 8**.

It would be great if you could support at least Java 7 and NetNeans 8.0.x even if this may oblige you to recompile Darcula LAF, otherwise clearly indicate the minimum Java/NetBeans version required in the plugin information page.

**Comment by Revivius** [comment]
@AlexFalappa; thank you for reporting, fixed. Uploaded new nbm compiled with Java 7. Also updated information on plugin page:

http://plugins.netbeans.org/plugin/62424/?show=true
