### ISSUE TITLE
Some more icons need tweaking

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#3]
![image](https://cloud.githubusercontent.com/assets/1857095/12431576/8650771a-bef6-11e5-9f30-e32ac0c33078.png)

Continue your good work!

**Comment by Revivius** [comment]
Done:
![multirow-icons](https://cloud.githubusercontent.com/assets/7155989/12525265/d1963788-c16b-11e5-9b33-85c88069b603.png)
