### ISSUE TITLE
Multi level dropdowns don't have arrow indicating sub menu until hover event

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#31]
Notice how the "composer" menu item doesn't have an arrow or any other icon indicating that it has another dropdown. When you hover over it however, it does display. Even if this is by design, I think we still need to have the arrows (just slightly transparent) so that we know there are more options.

![screen shot 2016-01-25 at 11 07 14 am](https://cloud.githubusercontent.com/assets/6099427/12546700/3e455cd0-c354-11e5-95d8-4e26e1dc759d.png)
![screen shot 2016-01-25 at 11 07 10 am](https://cloud.githubusercontent.com/assets/6099427/12546702/3ea31f14-c354-11e5-9ecb-d8e3c8da90c4.png)

**Comment by markiewb** [comment]
![2016-01-25_20h29_35](https://cloud.githubusercontent.com/assets/1857095/12561861/7c68477c-c3a2-11e5-8bec-15cc1445b236.png)
IMO this is not by design, IDEA15 has such an arrow. See the screenshot @Windows7

**Comment by Revivius** [comment]
@dylanvorster This is not the case on Windows, should be something to do with Aqua.

**Comment by Revivius** [comment]
@dylanvorster in fact arrow icon is there but its color is very hard to recognize (just zoom into the screenshot you provided). This is due to default icon provided by Aqua. Fixed by using standard Metal arrow icon. I would be happy if someone on MAC can verify the fix.
