### ISSUE TITLE
Compatibility to JDK7

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#32]
Strange. The new version 1.3.0 cannot be started at my working computer, which runs only JDK7. A previous version 1.0.0 IIRC worked using that configuration.

NB 8.1 still supports JDK7, so this plugin has to be compatible to JDK7 too.

![jdk7](https://cloud.githubusercontent.com/assets/1857095/12562037/4baad69e-c3a3-11e5-888a-1d622b5251d0.png)

**Comment by Revivius** [comment]
@markiewb did you update via IDE or downloaded from plugin page ? This was reported in #29 and I reuploaded the NBM (built by JDK7) to plugin portal but it is in verification. Until it passes the downloading manually should be ok.

**Comment by markiewb** [comment]
@Revivius: I updated it via IDE! I will give the manual way a try tomorrow. 

So please close this issue as duplicate of #29!
