### ISSUE TITLE
Disabled buttons are hard to read.

### ISSUE THREAD

**Issue by Revivius** [Revivius/nb-darcula#37]
Similar to disabled labels, buttons are hard to read:

![disabled-buttons](https://cloud.githubusercontent.com/assets/7155989/12591280/b15c1c88-c46f-11e5-83b2-6677da7e056d.png)

**Comment by Revivius** [comment]
![buttons-fix](https://cloud.githubusercontent.com/assets/7155989/12591477/9bb0de0e-c470-11e5-9cdd-73f9cd4723ea.png)

**Comment by markiewb** [comment]
Cool! Thanks!
