### ISSUE TITLE
"Search results" view has light border

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#39]
![image](https://cloud.githubusercontent.com/assets/1857095/12593086/8e016306-c46f-11e5-8493-902617713199.png)

EXPECTED: Dark border like the other views

**Comment by Revivius** [comment]
@markiewb, that is a hardcoded color and I dont know a good way of changing that (since it is not assigned to a field before usage). I reported this in NetBeans bugzilla see item 3:

https://netbeans.org/bugzilla/show_bug.cgi?id=257675

**Comment by markiewb** [comment]
Voted

**Comment by granella** [comment]
:+1: voted

**Comment by AlexFalappa** [comment]
Voted

**Comment by Revivius** [comment]
@markiewb do we need more votes for the bug ?

**Comment by markiewb** [comment]
Fixed.

https://netbeans.org/bugzilla/show_bug.cgi?id=257675#c5
