### ISSUE TITLE
Shortcut fonts in menu have a lower size

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#4]
![image](https://cloud.githubusercontent.com/assets/1857095/12431644/e2f13892-bef6-11e5-9ef5-e990eabdcb6b.png)

**Comment by Revivius** [comment]
Thank you for pointing; but this is the default behaviour of Darcula LAF and I believe it is fine, I dont think its is worthwhile to change.

**Comment by dylanvorster** [comment]
Im actually pretty sure that this is by design, so as to not steal attention away from the main menu items.

**Comment by markiewb** [comment]
@Revivius: It is not a default behaviour. See this screenshot of Idea15. It is the same font and color as the menu text.

![image](https://cloud.githubusercontent.com/assets/1857095/12462273/ac07d328-bfbd-11e5-9c28-b14cfbb713b5.png)

**Comment by markiewb** [comment]
So please reopen this issue!

**Comment by markiewb** [comment]
See also https://github.com/Revivius/nb-darcula/pull/12
