### ISSUE TITLE
"Action items" view: sorting icon in header is not styled

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#40]
![image](https://cloud.githubusercontent.com/assets/1857095/12593137/d07cd878-c46f-11e5-9749-3e2c58199cb9.png)

**Comment by Revivius** [comment]
![action-items-sort](https://cloud.githubusercontent.com/assets/7155989/12626478/933fa850-c541-11e5-9f07-4d7181286600.png)
