### ISSUE TITLE
Tree tables paint a dark border for the selected entry

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#42]
![2016-01-26_22h26_39](https://cloud.githubusercontent.com/assets/1857095/12595532/13f6beaa-c47c-11e5-8dba-bbb309489c99.png)

EXPECTED: No border

**Comment by markiewb** [comment]
@Revivius: Can you please review and merge the pull request?

**Comment by Revivius** [comment]
PR #63 fixinf this was merged. Closing.
