### ISSUE TITLE
Make differenc color for type and identifier

### ISSUE THREAD

**Issue by rniestroj** [Revivius/nb-darcula#43]
In Java Language the color for the parameter could be different that the color of it;s type like it is i think in norway today. In Norway today it has an orange color.  This would greatly enhance readability. See screenshots attached.
![norway-today](https://cloud.githubusercontent.com/assets/1690850/12612384/976b8c68-c4f2-11e5-96c5-135a27c390cb.jpg)
![darcula-laf](https://cloud.githubusercontent.com/assets/1690850/12612385/976dee72-c4f2-11e5-84a0-c7050b0b07be.jpg)

**Comment by Revivius** [comment]
@rniestroj; merging of PR #49 from @granella made the method declaration in different color now, not the parameter type but I hope that makes methods easier to use. I would like to consider this as closed, thank you for pointing out!
