### ISSUE TITLE
Hardcoded light backgrounds in task editors

### ISSUE THREAD

**Issue by AlexFalappa** [Revivius/nb-darcula#44]
Steps to reproduce:

1. Create a Bugzilla task repository in **Services > Task Repositories** 
1. Right click it and choose **Find Task...** 
1. Make a query, the result table has white background cells:
    ![findtasks](https://cloud.githubusercontent.com/assets/1875690/12616523/f78bac4a-c50b-11e5-9d92-3636634de7de.png)
1. Double click on a row to open the task in a detail editor
1. The comments section has text areas with light backgrounds and pale text:
    ![edittask](https://cloud.githubusercontent.com/assets/1875690/12616596/50fbdec6-c50c-11e5-9d7a-cf935314f15f.png)

**Comment by Revivius** [comment]
Fixed:

![bug-tracking](https://cloud.githubusercontent.com/assets/7155989/12657627/00e7e298-c60d-11e5-99a5-3774fd313fca.png)

**Comment by AlexFalappa** [comment]
Great!!!
