### ISSUE TITLE
Provide darker icons for breadcrumb separator

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#47]
![image](https://cloud.githubusercontent.com/assets/1857095/12628252/915e02f6-c542-11e5-8af7-d725d0126863.png)

**Comment by granella** [comment]
separator image is hardcoded in "private dependency"

```java
package org.netbeans.modules.editor.breadcrumbs;

public class BreadCrumbComponent<T extends JLabel&Renderer> 
                    extends JComponent implements PropertyChangeListener {

    private final Image SEPARATOR = ImageUtilities.loadImage("org/netbeans/modules/editor/breadcrumbs/resources/separator.png");

}
``
It's possible? with reflection?

**Comment by Saljack** [comment]
I think this lighter icons looks better than darker. It is hard to see this delimiter from Idea.

**Comment by Revivius** [comment]
I agree that current icons are easier to recognize and therefore would like to close this issue.

**Comment by markiewb** [comment]
That's OK for me not to change it.
