### ISSUE TITLE
Tooltips for disabled icons are bad readable

### ISSUE THREAD

**Issue by Saljack** [Revivius/nb-darcula#53]
Tooltips for disabled icons are bad readable. It is too dark.
![disable tooltip](https://cloud.githubusercontent.com/assets/614424/12670986/e1a24d28-c66c-11e5-8f03-992429428328.png)

**Comment by Revivius** [comment]
Fixed:
![disabled-tooltip](https://cloud.githubusercontent.com/assets/7155989/12683440/ee89497e-c6c1-11e5-9a66-daa766a83b43.png)

**Comment by AlexFalappa** [comment]
Mmmh, is it distinguishable from an enabled tooltip?

**Comment by Revivius** [comment]
Do they need to be ?

**Comment by AlexFalappa** [comment]
I think yes: enabled tooltip on enabled widget, disabled one on disabled widget.

In my opinion you should, if possible, maintain the difference, for example make the disabled tooltips gray (two contrasting shades for background and text).
