### ISSUE TITLE
Background color of some components not the same as standard Darcula library

### ISSUE THREAD

**Issue by granella** [Revivius/nb-darcula#61]
issue by  Tommy_Angelo from NB Plugin Portal.
See:
![before](https://cloud.githubusercontent.com/assets/859038/12704226/3f88e79a-c83d-11e5-9ad8-58af05be78e3.png)

"expected":
![after](https://cloud.githubusercontent.com/assets/859038/12704236/5764b02e-c83d-11e5-9bc8-9d352fed31b2.png)

**Comment by markiewb** [comment]
@Revivius: Can you please review and merge the pull request?

**Comment by markiewb** [comment]
@Revivius: Can you please review and merge the pull request? *push*

**Comment by Revivius** [comment]
@granella, @markiewb I was thinking having a slightly different background for lists, trees and tables would make them easier to recognize (without being disturbing). You both think we should merge this ?

**Comment by markiewb** [comment]
@Revivius: IMO it should be as near as possible to the original darcula. This way nobody reports "that looks different" issues anymore.

**Comment by granella** [comment]
@Revivius I agree with @markiewb

**Comment by Revivius** [comment]
PR #62 which fixes this was merged. Closing.
