### ISSUE TITLE
Notification "links" are too hard to read

### ISSUE THREAD

**Issue by phansson** [Revivius/nb-darcula#65]
This is issue was also discussed on the nbdev mailling list.

What you see below is a minimal NetBeans Platform application using nb-darcula 1.4.

![darculatest](https://cloud.githubusercontent.com/assets/1903550/12753563/ea014cd6-c9c7-11e5-82b4-5f0a4de8b935.png)

As can be seen it is very hard to read a standard [Notification](http://bits.netbeans.org/dev/javadoc/org-openide-awt/org/openide/awt/NotificationDisplayer.html) like the one displayed in the lower right corner of the main window.

The problem _isn't_ specific to nb-darcula. I'm doing NetBeans L&Fs myself (or at least attempting to) so I've come across the same problem with another dark'ish L&F that I'm using. I haven't found a way to solve it. The problem is with `NotificationImpl` in core.ui. If you look into the NB source you'll see that the clickable text isn't actually a link but is simply some underlined text (`<html><u> ....`) inside a JButton and then the implementation does :

`btn.setForeground(Color.blue);`

Ouch!

So the color is hardcoded. There's nothing that can be tweaked as far as I can see. If the question on the mailing list doesn't give a possible workaround then I'll log it as an enhancement request to NB and note the BugZilla id here when I do.

Thanks.

**Comment by phansson** [comment]
Someone has already logged this as an RFE on NetBeans:   https://netbeans.org/bugzilla/show_bug.cgi?id=246199. 

As far as I can tell the problem will solve itself - also in **nb-dracula** - when this code change is released.

**Comment by Revivius** [comment]
@phansson you are right; core.ui in NB 8.1 still has the hardcoded BLUE color and changing the "u" and "a" style colors as described in nbdev mailing list does not solve the problem, so we will have to wait until fix is released. Though I have problem understanding the dates in the NetBeans buzgilla. Fix seems to be merged at 2015-09-13 into main-silver and NetBeans NB 8.1 was released in 2015-11-04 according to NetBeans release history, so I think it should already have been there. What am I missing ?

**Comment by Revivius** [comment]
@phansson please vote for this issue for other hardcoded colors:

https://netbeans.org/bugzilla/show_bug.cgi?id=257675

Thank you!

**Comment by markiewb** [comment]
@Revivius: Ask ovrabec@netbeans.org (the dev, who applied the change)! Perhaps the version of the modules hasn't be changed and thus an old module has been included in NB8.1

I filed https://netbeans.org/bugzilla/show_bug.cgi?id=257823 and will ask Jirka for a change. Perhaps it can be still included in the upcoming 8.1patch1?!

**Comment by Revivius** [comment]
@markiewb  voted!

Do you think https://netbeans.org/bugzilla/show_bug.cgi?id=257675 will make it to 8.1patch1 ? Or it is too late for the patch?

**Comment by markiewb** [comment]
I writing an email to Jirka right now.

**Comment by markiewb** [comment]
@Revivius: BTW there are still 3 good pull requests to merge!

**Comment by neilcsmith-net** [comment]
@markiewb as just commented on the mailing list, check the original patch from that issue vs what was actually committed.  The patch might have fixed the issue, what was committed wouldn't.  The "fix" is probably already in there! :smile:

**Comment by Revivius** [comment]
@neilcsmith-net, @markiewb there are two NotificationImpl classes. Please see my post on dev mailing list:

http://forums.netbeans.org/viewtopic.php?p=168760#168760

**Comment by markiewb** [comment]
Fixed in NB8.2 
https://netbeans.org/bugzilla/show_bug.cgi?id=246199#c8

**Comment by Revivius** [comment]
@markiewb; thank you for fixing 

https://netbeans.org/bugzilla/show_bug.cgi?id=257675#c5

I checked your fixes in NB 8.2 and they are all great except: 

![diff-right-gutter](https://cloud.githubusercontent.com/assets/7155989/19092455/60439ae2-8a8f-11e6-9dd0-21eaf7dd5dea.png)

**Comment by Revivius** [comment]
Fixed by @markiewb in NetBeans 8.2:

https://netbeans.org/bugzilla/show_bug.cgi?id=246199#c8

Thank you @markiewb for making NB look better in dark LAFs.

**Comment by markiewb** [comment]
@Revivius: 
> I checked your fixes in NB 8.2 and they are all great except:

Filed https://netbeans.org/bugzilla/show_bug.cgi?id=268544
