### ISSUE TITLE
SSH and terminal tabs background

### ISSUE THREAD

**Issue by kowern** [Revivius/nb-darcula#66]
Background of SSH panel and background of terminal tabs is too bright. Today the background changed to gray for a while and it was great but after a while returned to the bright background. Same issue in Jira task comments.

![terminal](https://cloud.githubusercontent.com/assets/16614575/12754615/23e3bf5c-c9cc-11e5-8e66-c210a5a9db88.jpg)

![ssh](https://cloud.githubusercontent.com/assets/16614575/12754614/23e055ec-c9cc-11e5-98d9-03b2c8ff11c8.jpg)

**Comment by Revivius** [comment]
@kowern; screenshots you provided are rather strange. It looks like LAF was somehow partially applied. This is how it looks for me:

![ssh](https://cloud.githubusercontent.com/assets/7155989/12763187/bc88660c-c9fb-11e5-9e66-1f3faba53686.png)

Anything in NetBeans logs ?

**Comment by markiewb** [comment]
![2016-02-02_21h44_37](https://cloud.githubusercontent.com/assets/1857095/12763705/2dca787e-c9f6-11e5-8708-1b8cd834dde3.png)

Same for me. It works

Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java: 1.8.0_71; Java HotSpot(TM) 64-Bit Server VM 25.71-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_71-b15
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)

**Comment by kowern** [comment]
In fact problem is caused by Terminal Extra plugin. I disabled it and everything works properly. LAF is great!

**Comment by Revivius** [comment]
@kowern good to know it works for you too! Closing this issue.
