### ISSUE TITLE
SQL autocomplete hard to read field colours

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#67]
![screen shot 2016-02-03 at 11 19 40 am](https://cloud.githubusercontent.com/assets/6099427/12777895/44fe6be6-ca68-11e5-863d-7f9d63843b73.png)

The dark blue keywords, are slightly hard to read, perhaps use the same colour as the entities below it or use a slightly lighter shade to still help differentiate between the different types of entities.

**Comment by Revivius** [comment]
@dylanvorster this is due to more hardcoded colors in:

http://hg.netbeans.org/main/file/26a46bf0558d/db.sql.editor/src/org/netbeans/modules/db/sql/editor/completion/SQLCompletionItem.java

**Comment by markiewb** [comment]
@Revivius: Please file an issue! In the meantime we could override it via reflection?

**Comment by Revivius** [comment]
@markiewb I belive so; it should be easy to fix with reflection.

**Comment by Revivius** [comment]
Fixed:

![sql_columns](https://cloud.githubusercontent.com/assets/7155989/12830523/6f75a750-cb98-11e5-85c9-b5c4918a8048.png)
