### ISSUE TITLE
Upgrade POM to NetBeans 8.1

### ISSUE THREAD

**Issue by phansson** [Revivius/nb-darcula#68]
The POM seems to still reference `RELEASE80`.

**Comment by Saljack** [comment]
Why? Now you can use this LAF with Netbeans 8.0 too.

**Comment by markiewb** [comment]
@Revivius: @Saljack is correct. I would leave it at `RELEASE80` to support NB8.0+

I propose to close this issue as wontfix

**Comment by Revivius** [comment]
@phansson; I also would like to keep supporting NB 8.0 too (at least for the moment). Would it be inconvenient for you to clone the repo and change version to RELEASE81 for your own application ?

**Comment by phansson** [comment]
Yeah, sorry I was being selfish. I'm trying to use - or at least testing out - `darcula-nb` in an NetBeans Platform application context, as opposed to the IDE itself. Doing this type of testing I was building the project from sources and then this came about. 

Agree to close.

**Comment by Revivius** [comment]
@phansson any feedback about usage in a standalone application is wellcome. Thank you!
