### ISSUE TITLE
C/C++ Build hosts > New Remote host Setup > SSH Column [deep-edged icon issue]

### ISSUE THREAD

**Issue by dylanvorster** [Revivius/nb-darcula#70]
When trying to configure remote build hosts, the Network Table shows the ports as open / closed etc.. But these for some reason, were originally implemented as icons as apposed to being rendered with Graphics2D? They therefore appear deep-edged with traces of white making them basically unreadable. I might need to file a bug for this on the core so that we can provide an adapter or something to render our own icons.

![screen shot 2016-02-03 at 10 40 12 pm](https://cloud.githubusercontent.com/assets/6099427/12796504/c3bd9eca-cac7-11e5-88a3-4a6e40587985.png)

I know these aren't easy, and I'm well aware they will probably need some reflection hack, but this one is particularly bad.

**Comment by Revivius** [comment]
Node and SSH column icons fixed:

![cnd-remote](https://cloud.githubusercontent.com/assets/7155989/12828948/15800f36-cb90-11e5-85d6-0aaebe70957c.png)
