### ISSUE TITLE
Check if the theme-setup reflection code can be replaced with offical API-calls

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#72]
In Installer.java reflection is used to set the theme. Perhaps it is possible to use the official public API from org.netbeans.swing.plaf.Startup

http://bits.netbeans.org/dev/javadoc/org-netbeans-swing-plaf/org/netbeans/swing/plaf/Startup.html#run-java.lang.Class-int-java.net.URL-java.util.ResourceBundle-

**Comment by Revivius** [comment]
@markiewb; I think **theme** mentioned there is not the **Editor Theme** that we are setting with reflection in Installer.java:

http://hg.netbeans.org/main/file/26a46bf0558d/o.n.swing.plaf/src/org/netbeans/swing/plaf/Startup.java#l233

and NbTheme is

> An extension of javax.swing.plaf.metal.DefaultMetalTheme which can read a an xml file named <code>themes.xml</code> and apply the theme defined in XML.

http://hg.netbeans.org/main/file/26a46bf0558d/o.n.swing.plaf/src/org/netbeans/swing/plaf/util/NbTheme.java

**Comment by markiewb** [comment]
Oh. I wasn't aware of that. I close this issue.
