### ISSUE TITLE
Icon for profiler dropdown should be "darkified"

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#75]
![unnamed](https://cloud.githubusercontent.com/assets/1857095/13027680/6d127f9e-d258-11e5-9aa1-6aed8576b995.png)

**Comment by Revivius** [comment]
Fixed many icons related to Profiler UI:

![profiler-icons](https://cloud.githubusercontent.com/assets/7155989/13408379/39a7a64e-df36-11e5-9e7d-f69f3d0783f2.png)
