### ISSUE TITLE
Tabheader scroller buttons have borders and non-"darkified" icons

### ISSUE THREAD

**Issue by markiewb** [Revivius/nb-darcula#77]
![2016-02-13_14h15_44](https://cloud.githubusercontent.com/assets/1857095/13027764/50fa0ac6-d25c-11e5-981c-423fc1d50b7e.png)

**Comment by Revivius** [comment]
Fixed:

![scroll-button](https://cloud.githubusercontent.com/assets/7155989/13382339/dbe14f6c-de7a-11e5-9d93-1c2bed575752.png)
