### ISSUE TITLE
Colors in code completion for JSF components tags in jspx files are not readable

### ISSUE THREAD

**Issue by marioserrano09** [Revivius/nb-darcula#79]
![codecompletion](https://cloud.githubusercontent.com/assets/5221275/13202666/477c54d0-d870-11e5-9b0c-ccab76f811bc.png)

**Comment by granella** [comment]
see PR #73

**Comment by markiewb** [comment]
@granella: So #79 is already solved by #73 ?

**Comment by granella** [comment]
@markiewb yea! ;)

**Comment by markiewb** [comment]
@Revivius: So please close this issue as duplicate!
