### ISSUE TITLE
Low contrast for popup drop-down lists in SQL editor for field names

### ISSUE THREAD

**Issue by DVader666** [Revivius/nb-darcula#80]
In the NB SQL editor, when using code completion while working with queries, the drop-down list popup contains low contrast colors for DB table field names: dark background with dark blue font color (for items not currently selected in the list).

Currently using NB 8.1 (up to date).

![image](https://cloud.githubusercontent.com/assets/17498743/13357757/841f1ddc-dc71-11e5-8787-ad6301cb52d7.png)

**Comment by AlexFalappa** [comment]
Duplicate of #67.
Already fixed but not released yet.

**Comment by Revivius** [comment]
@DVader666 fix will be available in v1.5. Thank you for reporting.
