### ISSUE TITLE
No text baseline alignment for combobox labels

### ISSUE THREAD

**Issue by AlexFalappa** [Revivius/nb-darcula#81]
The problem mainly shows in the options dialog, for exemple here:
![nb-combo-before-2](https://cloud.githubusercontent.com/assets/1875690/13372850/ebf87d60-dd55-11e5-9ad7-8cabd0f8b5d8.png)
And here:
![nb-combo-before](https://cloud.githubusercontent.com/assets/1875690/13372852/efac9d42-dd55-11e5-8551-78e6e524f7c2.png)

**Comment by AlexFalappa** [comment]
The problem is in the original Darcula Look And Feel.
I have fixed it and submitted PR https://github.com/bulenkov/Darcula/pull/18 to the original project.
With a custom built look and feel jar the options dialog is now:
![nb-combo-after-2](https://cloud.githubusercontent.com/assets/1875690/13372870/af11a39e-dd56-11e5-80dd-5f17c0abcc1f.png)
And:
![nb-combo-after](https://cloud.githubusercontent.com/assets/1875690/13372872/ca8a58dc-dd56-11e5-9caf-6dd24ce6d67a.png)

**Comment by AlexFalappa** [comment]
The fix is also available in [my fork of the Darcula Look And Feel](https://github.com/AlexFalappa/Darcula)

**Comment by markiewb** [comment]
@Revivius: How about including the jar of @AlexFalappa's fork instead of the original?

**Comment by Revivius** [comment]
@markiewb I think it is a very good idea to include @AlexFalappa's fork because original repo seems to be inactive for quite some time. Lets target this for v1.5

**Comment by AlexFalappa** [comment]
@Revivius thanks for considering my contributions.

Here is the complete list of my fork improvements over the original Darcula LAF:

- [Restore JComboBox baseline calculation](https://github.com/bulenkov/Darcula/pull/18): shown above
- [Better icons for JOptionPane](https://github.com/bulenkov/Darcula/pull/15): this is based on my previous PR to nb-darcula #59, but adds HiDPI version of the icons and eliminates some transparency fringing on normal icons
- [Fix possible ArrayOutOfBoundsException in DarculaSpinnerUI](https://github.com/bulenkov/Darcula/pull/14): this "backported" the spinner improvements made in nb-darcula to the Darcula LAF
- [Darcula JToggleButton LAF support](https://github.com/bulenkov/Darcula/pull/13): this adds support for `JToggleButton` that otherwise retains the appearance of the Metal LAF with dark colors

**Comment by Revivius** [comment]
@AlexFalappa how should we proceed ? Your improvements will render some classes in ui package obsolete. Is it possible for you to create a pull request containing the JAR built from your fork and removes unrequired class in plugin source ?

**Comment by AlexFalappa** [comment]
@Revivius sure, I will try to cook up something this evening.

**Comment by AlexFalappa** [comment]
Done as PR #86

**Comment by AlexFalappa** [comment]
I see that the PR has diverged from master, would you like me to rebase?

**Comment by Revivius** [comment]
@AlexFalappa; yes please. I want to check and merge this PR as soon as possible. I am sorry for the delay.

**Comment by AlexFalappa** [comment]
Made a better PR #89.
Apologies for my delay too

**Comment by AlexFalappa** [comment]
Will close my previous PR

**Comment by AlexFalappa** [comment]
@Revivius you should be able to merge cleanly now

**Comment by Revivius** [comment]
@AlexFalappa; merged, thank you for combobox baseline fix. 

Next time we should consider updating the version of the jar in lib folder. Files in lib folder (which we declare as a repo in pom) seems to be copied to local maven repo (under user home) during build. Since there already was a com.bulenkov.darcula-1.0.0.jar in my local repo I had hard time understanding why your fixes was not working. Deleting the jar from my local maven repo (again under user home) caused the updated jar (in lib folder from your PR) to be copied to there and until that point I could see modifications to jar within NetBeans and also build started to use new jar so I could see your fixes.

**Comment by AlexFalappa** [comment]
@Revivius good to know that.
I was also thinking to change the maven coordinates of my fork to better distinguish it from the original one (changing the group id for example).
