### ISSUE TITLE
Possible to redesign the options menu?

### ISSUE THREAD

**Issue by Chris2011** [Revivius/nb-darcula#84]
I don't like the options menu of netbeans much, but I really like the options menu of Visual Studio: https://visualstudioaddins.files.wordpress.com/2012/01/vscoloroutput-settings-in-the-visual-studio-options-dialog.png

and the Options menu of IntelliJ: http://blog.jetbrains.com/idea/files/2015/03/gradle-jvm.png

both are similar to each other. Netbeans looks not that really nice, in my perspective. So my question is, is it possible to redesign the options window with the darcula laf?

**Comment by Chris2011** [comment]
Is this technical possible with only the darcula laf?

**Comment by markiewb** [comment]
IMO No it is not possible. 

In the past there has been a tree-like vertical options menu

See https://benkiew.files.wordpress.com/2014/02/2014-02-28_20h56_12.png and https://blogs.oracle.com/geertjan/entry/options_options_we_want_options

**Comment by Revivius** [comment]
@Chris2011, no it is not feasibly possible with LAF.

**Comment by Chris2011** [comment]
@markiewb thx for the info, I really liked the old one as real tree's because you can see everything you want. The new one isn't so good. But ok I understand that this is not possible with LAF's thx.
