### ISSUE TITLE
Same background colors for files

### ISSUE THREAD

**Issue by 4ppleboy** [Revivius/nb-darcula#85]
![screenshot_2016-03-16_11-24-46](https://cloud.githubusercontent.com/assets/3277751/13802851/aa5d9394-eb61-11e5-959d-e1ebe621758a.jpg)

**Comment by markiewb** [comment]
@4ppleboy: What is the problem? What is expected?

**Comment by 4ppleboy** [comment]
if check option 'Same background color for files from same project' background only one of the matches with LAF, other colors is default NB colors
