### ISSUE TITLE
Customize tabs

### ISSUE THREAD

**Issue by Deorro** [Revivius/nb-darcula#87]
As I can make it go away with the gradient buttons, I need to have only a flat uniform color, such as Intellij, no gradient and brightness as shown in the image.

As seen my Netbeans:

![Screenshot01](http://i.imgur.com/P08wNJJ.png)

As I want you to see:

![Screenshot02](http://i.imgur.com/3tFRWda.png)

**Comment by Revivius** [comment]
@Deorro; thank you for pointing out but  I dont think we should aim for exact Idea look.

**Comment by Chris2011** [comment]
Is an option possible to change the look of such tab? So you don't need to change them but it should be customizable. I really would like to have this feature too.

**Comment by markiewb** [comment]
For the record: It's possible, but this requires some effort.

https://blogs.oracle.com/netbeanstips/entry/customize_document_tabs_in_netbeans
