### ISSUE TITLE
hard to read colors Sass

### ISSUE THREAD

**Issue by ibaianater** [Revivius/nb-darcula#91]
There is a problem with sass variables. it's hard to read colors.

<img src="http://i.imgur.com/f5ladHC.png" alt="img" />

**Comment by Revivius** [comment]
Fixed:

![css-prep](https://cloud.githubusercontent.com/assets/7155989/14445051/b40d73d6-0052-11e6-9726-abbab1757e2e.png)

**Comment by Chris2011** [comment]
It still happens for variables and mixins in NB 8.2.
