### ISSUE TITLE
Colors in code completion for SpringBoot application properties are not readable

### ISSUE THREAD

**Issue by AlexFalappa** [Revivius/nb-darcula#94]
Completion color in NetBeans Spring Boot application properties support (https://github.com/keevosh/nb-springboot-configuration-support) is hardcoded to dark blue.

**Comment by AlexFalappa** [comment]
I will submit a PR fixing this issue.

**Comment by AlexFalappa** [comment]
I would like to submit a PR to the plugin project correcting the use of the hardcoded color in the first place, what's the best way to use colors in a theme friendly way?

If it's best to retrieve colors from `UIManager` defaults what's the best key to use?

**Comment by Revivius** [comment]
I believe using UIManager is the way to go but I dont think there is a general color key (assuming you are referring to standard Swing or AWT keys) that would work for all possible LAFs.

**Comment by AlexFalappa** [comment]
Fixed with PR #95

**Comment by AlexFalappa** [comment]
Closing this issue.

I made the [NB Spring Boot](https://github.com/AlexFalappa/nb-springboot) plugin to support programming with Spring and Spring Boot which does not suffer from this.
