### ISSUE TITLE
Menu icons faded and unrecognizable

### ISSUE THREAD

**Issue by ee-usgs** [Revivius/nb-darcula#99]
The menu icons are so muted that they are unrecognizable - See the icons near the top of my screen in this screenshot:
![screen shot 2016-04-26 at 10 01 34 am](https://cloud.githubusercontent.com/assets/3370644/14822943/2fc38e86-0b96-11e6-958d-cabf34ccf41d.png)

Doing a bit of googling, I didn’t see anyone else reporting this issue, but someone else posted a screenshot of the theme in use w/ the same issue but didn’t mention the issue.  See the first screenshot here:
http://blog.bobbyallen.me/2016/01/17/jetbrains-dark-theme-dracula-for-netbeans/

System info is in my screenshot, but here is the summary:
Darcula 1.5
NetBeans 8.1 Patch 1
Java 1.8.0_51
OS X 10.11.4

**Comment by Revivius** [comment]
@ee-usgs; I cant see the problem. Can you explain what is wrong please ?

**Comment by ee-usgs** [comment]
After comparing this to the standard OS X theme, it turns out the menu icons are actually the same.  Here is a capture of the standard theme icons in disabled state:
![screen shot 2016-04-26 at 12 53 37 pm](https://cloud.githubusercontent.com/assets/3370644/14828758/fa20e37e-0bad-11e6-8620-4ee324d9721f.png)
and the Darcula version for direct comparison:
![screen shot 2016-04-26 at 12 59 10 pm](https://cloud.githubusercontent.com/assets/3370644/14828962/dea73f16-0bae-11e6-8392-6417679f7cc6.png)

The issue is, I believe, that the icons are intended to look disabled ***on a light grey background***.  They just look broken on a dark grey background.  The contrast between the Dracula dark grey background and the light grey disabled icons makes them look like they have no color at all.  It would be nice to think that you could change the background color behind an icon and everything would just work but I don’t think that is the case.

**Comment by Revivius** [comment]
@ee-usgs; oh ok you mean disabled icons **in toolbar**. Well I dont agree that they look broken but I think you are right to some extent that they look *less detailed*. But again; since they are disabled and hence are supposed to request less attention that is not a problem.

**Comment by markiewb** [comment]
@ee-usgs: Check the invert color option from #41. Perhaps that suits better in your eyes.

The icons look like that ![2016-01-26_21h53_43](https://cloud.githubusercontent.com/assets/1857095/12595337/0931321c-c47b-11e5-9ea2-bb9158b37a8d.png)

**Comment by Revivius** [comment]
@ee-usgs please consider @markiewb's suggestion regarding icons.
Closing the issue.

**Comment by ee-usgs** [comment]
Thank you for the replies.  Using the ‘Invert icon colors’ option does help a bit.  

After looking at what this option does, I’d suggest renaming that to something like:
**Invert icon color *values* (light and dark levels)**
Its not the colors that are being inverted - its the light and dark levels.

**Comment by markiewb** [comment]
@ee-usgs: Propose a catchy name and we will change it!

**Comment by ee-usgs** [comment]
I would propose this exact text:
**Invert icon color values (light and dark levels)**
